services:

  postgres:
    image: postgres:17
    container_name: postgres

    environment:
      POSTGRES_DB: projetos_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  backend:
    build: .

    container_name: backend

    depends_on:
      - postgres

    ports:
      - "8080:8080"

    restart: unless-stopped

volumes:
  postgres_data: